config/routes.rb
Rails.application.routes.draw do
  resources :administrations
  post '/administrations/:id/users', to: 'administrations#add_user', as: 'add_user_to_administration'
  delete '/administrations/:id/users/:user_id', to: 'administrations#remove_user', as: 'remove_user_from_administration'

  resources :signalements do
    member do
        post :publish
    end
  end
  
  devise_for :users, path: 'account', controllers: { registrations: 'users/registrations' }
  get '/account', to: 'account#show'
  
  resources :users, only: [:index, :show, :update]

  post '/ds/event', to: 'ds#event'
  get '/ds/dossiers', to: 'ds#index'

  get '/srj/nataffs', to: 'srj#nataffs'
  get '/srj/natinfs', to: 'srj#natinfs'

  root "index#index"
end

app/models/signalement.rb
class Signalement < ApplicationRecord
    belongs_to :createur, class_name: 'User', foreign_key: 'createur_id', required: true
    belongs_to :administration, required: true

    has_and_belongs_to_many :nataffs
    has_and_belongs_to_many :natinfs

    has_many_attached :documents

    default_scope { includes(:createur, :administration, :nataffs, :natinfs) }

    enum status: {
        draft: 0,
        sent: 1,
        closed: 2
    }
end

app/controllers/signalements_controller.rb
class SignalementsController < ApplicationController
  before_action :authenticate_user!
  before_action :enrolled_user!
  before_action :set_signalement, only: %i[ show edit update destroy publish ]

  # GET /signalements or /signalements.json
  def index
    @search = params[:search]
    @urgence = ["true", "oui", "1", 1].include? params[:urgence]
    @page = params[:page].to_i || 0
    @limit = !params[:limit] || params[:limit].to_i <= 0 ? 10 : params[:limit].to_i

    #manager/user -> all signalements for admin
    #root -> all signalements
    query = nil
    if current_user.role_root?
        query = Signalement
    else
        query = Signalement.where administration_id: current_user.administration_id
    end


    if @urgence
        query = query.where urgence: true
    end

    if @search
        query = query.where(
            'reference_administration ILIKE :startswith
            OR idj ILIKE :startswith
            OR lieux_faits ILIKE :contains', 
            startswith: "#{@search}%",
            contains: "%#{@search}%"
        )
    end

    @pageCount = query.count() / @limit
    @signalements = query.limit(@limit).offset(@page*@limit)
  end

  # GET /signalements/1 or /signalements/1.json
  def show
  end

  # GET /signalements/new
  def new
    @signalement = Signalement.new
    @signalement.administration = current_user.administration
    @signalement.createur = current_user
  end

  # GET /signalements/1/edit
  def edit
    if !@signalement.draft?
        respond_to do |format|
            format.html { redirect_to @signalement, flash: { error: "Impossible de modifier un signalement déjà envoyé !"} }
            format.json { render json: "Impossible de modifier un signalement déjà envoyé !", status: :unprocessable_entity }
        end
        return
    end
  end

  # POST /signalements or /signalements.json
  def create
    @signalement = Signalement.new(signalement_params)
    @signalement.administration_id = current_user.administration_id
    @signalement.createur = current_user

    set_signalement_nataffs
    set_signalement_natinfs

    respond_to do |format|
      if @signalement.save
        format.html { redirect_to @signalement, notice: "Signalement créé avec succès !" }
        format.json { render :show, status: :created, location: @signalement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @signalement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signalements/1 or /signalements/1.json
  def update
    if !@signalement.draft?
        respond_to do |format|
            format.html { redirect_to @signalement, flash: { error: "Impossible de modifier un signalement déjà envoyé !"} }
            format.json { render json: "Impossible de modifier un signalement déjà envoyé !", status: :unprocessable_entity }
        end
        return
    end

    set_signalement_nataffs
    set_signalement_natinfs

    respond_to do |format|
      if @signalement.update(signalement_params)
        format.html { redirect_to @signalement, notice: "Signalement mis-à-jour avec succès !" }
        format.json { render :show, status: :ok, location: @signalement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @signalement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signalements/1 or /signalements/1.json
  def destroy
    @signalement.destroy
    respond_to do |format|
      format.html { redirect_to signalements_url, notice: "Signalement détruit avec succès !" }
      format.json { head :no_content }
    end
  end

  def publish 
    if !@signalement.draft?
        respond_to do |format|
            format.html { redirect_to @signalement, flash: { error: "Le signalement a déjà été envoyé !"} }
            format.json { render json: "Le signalement a déjà été envoyé !", status: :unprocessable_entity }
        end
        return
    end

    @signalement.sent!

    respond_to do |format|
        if @signalement.save

            SendSignalementJob.perform_later @signalement

            format.html { redirect_to @signalement, notice: "Signalement envoyé avec succès !" }
            format.json { render :show, status: :ok, location: @signalement }
        else
            format.html { render :show, status: :unprocessable_entity }
            format.json { render json: @signalement.errors, status: :unprocessable_entity }
        end
    end
  end

  private
    def set_signalement_nataffs
        begin
            nataffs = JSON.parse(params[:signalement][:nataffs])
            @signalement.nataffs = Nataff.where(code: nataffs)
        rescue => e
            puts e
            puts "Invalid Nataff, ignoring..."
        end
    end

    def set_signalement_natinfs
        begin
            natinfs = JSON.parse(params[:signalement][:natinfs])
            @signalement.natinfs = Natinf.where(numero: natinfs)
        rescue => e
            puts e
            puts "Invalid Natinf, ignoring..."
        end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_signalement
      @signalement = Signalement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def signalement_params
      params.require(:signalement).permit(:urgence, :reference_administration, :commentaire, :lieux_faits, :date_faits, documents: [])
    end
end

app/helpers/signalements_helper.rb
module SignalementsHelper
end

app/views/signalements/_form.html.erb
<%= form_with(model: signalement) do |form| %>
    <% if signalement.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(signalement.errors.count, "error") %> prohibited this signalement from being saved:</h2>

        <ul>
        <% signalement.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <h3>Informations générales</h3>

    <%= form.ip_text_field(
        :reference_administration, 
        label: "Référence pour l'administration",
        hint: "numéro d'identification interne pour ce dossier au sein de votre administration (optionnel)."
    )%>

    <%= form.ip_text_field(
        :date_faits,
        label: "Date des faits",
        hint: 'Pour un évenement ponctuel : "01/02/2021", pour une periode, "de mars à mai 2021" ou "du 01/03/2021 au 30/04/2021".'
    )%>

    <%= form.ip_tags_input(
        :lieux_faits,
        label: "Lieux des faits",
        hint: "Lieux dans lesquels l'infraction a été commise",
        tags: signalement.lieux_faits ? signalement.lieux_faits : [],
        data_source: "api-communes"
    )%>

    <%= form.ip_check_box(
        :urgence,
        label: "Il s'agit d'un urgence",
        hint: "Un dossier urgent fera l'object d'un traitement prioritaire de la part du parquet réceptionnant la procédure."
    )%>

    <h3>Qualification</h3>

    <%= form.ip_tags_input(
        :nataffs,
        label: "Code(s) NATAFF",
        hint: "Aide le bureau d'ordre à orienter le dossier vers les personnes compétentes. Si innconnu, laisser vide ou utiliser la fonctionnalité d e recherche.",
        tags: signalement.nataffs ? (signalement.nataffs.map {|nataff| {value: nataff["code"], desc: nataff["desc"]}}).to_json : [],
        data_source: "api-nataffs",
        query_threshold: 1
    )%>
    <%= form.ip_tags_input(
        :natinfs,
        label: "numéro(s) NATINF",
        hint: "Aide le bureau d'ordre à orienter le dossier vers les personnes compétentes. Si innconnu, laisser vide ou utiliser la fonctionnalité d e recherche.",
        tags: signalement.natinfs ? (signalement.natinfs.map {|natinf| {value: natinf["numero"], desc: natinf["desc"]}}).to_json : [],
        data_source: "api-natinfs",
        query_threshold: 1
    )%>

    <%= form.ip_text_area(
        :commentaire,
        label: "Commentaire",
        hint: "Facultatif"
    )%>

    <h3>Documents attachés</h3>

    <%= form.ip_file_field(
        :documents,
        multiple: true,
        label: "Ajouter des documents au signalement",
        hint: "Taille maximale : 1Go, tous les formats supportés, plusieurs fichiers possibles.",
        files: signalement.documents
    )%>


    <div class="actions">
        <br />
        <%= form.submit action_name == "new" ? "Créer la procédure" : "Sauvegarder les changements", class: "fr-btn" %>
    </div>
<% end %>

app/views/signalements/_signalements.html.erb
<div class="fr-table">
    <table>
    <caption></caption>
    <thead>
        <tr>
        <th>Reference administration</th>
        <th>Identifiant Justice</th>
        <th>Nature de l'affaire</th>
        <th>Date des faits</th>
        <th>Lieux des faits</th>
        <th>Urgence</th>
        <th>Status</th>
        <th colspan="2">actions</th>
        </tr>
    </thead>

    <tbody>
        <% @signalements.each do |signalement| %>
        <tr class="<%= signalement.urgence ? 'dossier-urgent' : ''%>">
            <td><%= signalement.reference_administration %></td>
            <td><%= signalement.idj %></td>
            <td><%= (signalement.nataffs.map { |nataff| nataff.code }).join ', ' %></td>
            <td><%= signalement.date_faits%></td>
            <td><%= JSON.parse(signalement.lieux_faits).join ', ' %></td>
            <td>
                <% if signalement.urgence %> 
                    <span class="fr-fi-error-warning-fill" aria-hidden="true"></span>
                <% else %>
                    Non
                <% end %>
            </td>
            <td>
                <% if signalement.draft? %>
                    Brouillon
                <% elsif signalement.sent? %>
                    Envoyé
                <% else %>
                    Archivé
                <% end %>
            </td>
            <td>
                <%= link_to signalement, class: "fr-link", title: 'Voir' do %>
                    <span class="fr-fi-eye-line"></span>
                <% end %>
            </td>
            <td>
                <% if signalement.draft? %>
                    <%= link_to edit_signalement_path(signalement), class: "fr-link", title: 'Modifier' do %>
                        <span class="fr-fi-edit-line"></span>
                    <% end %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>
<nav role="navigation" class="fr-pagination" aria-label="Pagination">
    <ul class="fr-pagination__list">
        <li>
            <%= link_to 'Première page', request.query_parameters.merge({:page => 0}), class: "fr-pagination__link fr-pagination__link--first" %>
        </li>
        <li>
            <% if @page > 0 %>
                <%= link_to 'Page précédente', request.query_parameters.merge({:page => @page - 1}), class: "fr-pagination__link fr-pagination__link--prev fr-pagination__link--lg-label" %>
            <% else %>
                <a class="fr-pagination__link fr-pagination__link--prev fr-pagination__link--lg-label">Page précédente</a>
            <% end %>
        </li>
        <% @pageCount.times do |i| %>
            <%= link_to i+1, request.query_parameters.merge({:page => i}), class: "fr-pagination__link", "aria-current": i == @page ? "page" : nil %>
        <% end %>
        <li>
            <% if @page < @pageCount - 1 %>
                <%= link_to 'Page suivante', request.query_parameters.merge({:page => @page + 1}), class: "fr-pagination__link fr-pagination__link--next fr-pagination__link--lg-label" %>
            <% else %>
                <a class="fr-pagination__link fr-pagination__link--next fr-pagination__link--lg-label">
                    Page suivante
                </a>
            <% end %>
        </li>
        <li>
            <a class="fr-pagination__link fr-pagination__link--last" href="#">
                Dernière page
            </a>
        </li>
    </ul>
</nav>

app/views/signalements/edit.html.erb
<h1>Editer un signalement</h1>

<%= render 'form', signalement: @signalement %>

<%= link_to 'Voir', @signalement, class: "fr-link" %> |
<%= link_to 'Retour', signalements_path, class: "fr-link" %>

app/views/signalements/index.html.erb
<h1>
    Mes procédures 
    <%= link_to "Créer une nouvelle procédure", new_signalement_path, class: "fr-btn" %>
</h1>
<div id="dossier-filters">
    <div class="fr-checkbox-group">
        <input 
            type="checkbox"
            id="ds-index-checkbox-urgence" 
            name="checkbox" 
            onclick="InfoParquet.signalements.index.toggleDossierUrgent(event, this, '<%= request.query_parameters %>')"
            <%= ["true", "oui", "1", 1].include?(request.query_parameters["urgence"]) ? "checked" : nil %>
        >
        <label class="fr-label" for="ds-index-checkbox-urgence">seulement les dossiers urgents</label>
    </div>

    <%= form_with method: "get" do |form| %>
        <div class="fr-search-bar" id="header-search" role="search">
        <label class="fr-label" for="search-1">
            Recherche
        </label>
        <input type="hidden" name="urgence" value="<%= request.query_parameters["urgence"] || "false" %>">
        <input class="fr-input" placeholder="Rechercher" type="search" id="search-1" name="search" value="<%= @search %>">
        <button type="submit" class="fr-btn" title="Rechercher">
            Rechercher
        </button>
        </div>
    <% end %>
</div>
<div id="dossier-container">
    <%= render "signalements" %>
</div>

<%= javascript_pack_tag 'signalements/index' %>

app/views/signalements/new.html.erb
<h1>Créer une nouvelle procédure</h1>

<%= render 'form', signalement: @signalement %>

<%= link_to 'Retour', signalements_path, class: "fr-link" %>

app/views/signalements/show.html.erb
<h1>
    Détails de la procédure

    <% if @signalement.draft? %>
        <div class="signalement_actions">
            <%= link_to 'Editer', edit_signalement_path(@signalement), class: "fr-btn fr-btn--secondary" %>
            <%= link_to 'Envoyer la procédure', publish_signalement_path(@signalement), method: :post, class: "fr-btn" %>
        </div>
    <% end %>
</h1>

<div id="signalement_content">
    <div id="signalement_data">
        <div class="fr-table">
            <table>
                <caption>Identité du demandeur</caption>
                <tbody>
                    <tr><th>Nom</th><td><%= @signalement.createur.nom %></td></tr>
                    <tr><th>Prénom</th><td><%= @signalement.createur.prenom %></td></tr>
                    <tr><th>E-mail</th><td><%= @signalement.createur.email %></td></tr>
                    <tr><th>Administration</th><td><%= @signalement.administration.nom %> (<%= @signalement.administration.service %>)</td></tr>
                </tbody>
            </table>
        </div>

        <div class="fr-table">
            <table>
                <caption>Informations générales</caption>
                <tbody>
                    <tr><th>Référence administration</th><td><%= @signalement.reference_administration %></td></tr>
                    <tr><th>date des faits</th><td><%= @signalement.date_faits %></td></tr>
                    <tr><th>Lieux des faits</th><td><%= JSON.parse(@signalement.lieux_faits).join ', ' %></td></tr>
                    <tr><th>Il s'agit d'une urgence</th><td><%= @signalement.urgence ? 'oui' : 'non' %></td></tr>
                </tbody>
            </table>
        </div>

        <div class="fr-table">
            <table>
                <caption>Qualification</caption>
                <tbody>
                    <tr><th>Code NATAFF:</th><td><%= (@signalement.nataffs.map { |nataff| nataff.code }).join ', ' %></td></tr>
                    <tr><th>Code NATINF:</th><td><%= (@signalement.natinfs.map { |natinf| natinf.numero }).join ', ' %></td></tr>
                    <tr><th>Commentaire:</th><td><%= @signalement.commentaire %></td></tr>
                </tbody>
            </table>
        </div>
    </div>

    <h4>Documents attachés</h4>
    <ul>
        <% @signalement.documents.each do |document| %>
            <li><a href="<%= rails_blob_path(document, disposition: "attachment") %>"><%= document.filename %></a></li>
        <% end %>
    </ul>
</div>