config/routes.rb
Rails.application.routes.draw do
  resources :administrations
  post '/administrations/:id/users', to: 'administrations#add_user', as: 'add_user_to_administration'
  delete '/administrations/:id/users/:user_id', to: 'administrations#remove_user', as: 'remove_user_from_administration'

  resources :signalements do
    member do
        post :publish
    end
  end
  
  devise_for :users, path: 'account', controllers: { registrations: 'users/registrations' }
  get '/account', to: 'account#show'
  
  resources :users, only: [:index, :show, :update]

  post '/ds/event', to: 'ds#event'
  get '/ds/dossiers', to: 'ds#index'

  get '/srj/nataffs', to: 'srj#nataffs'
  get '/srj/natinfs', to: 'srj#natinfs'

  root "index#index"
end

app/models/administration.rb
class Administration < ApplicationRecord
    has_many :users
end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
  before_action :authenticate_user!
  before_action except: [:add_user, :remove_user] do authorize_roles ['root'] end
  before_action only: [:add_user, :remove_user] do authorize_roles ['root', 'manager'] end
  before_action :set_administration, only: %i[ show edit update destroy add_user remove_user ]

  def index
    @administrations = Administration.all
  end

  def show
  end

  def new
    @administration = Administration.new
  end

  def edit
  end

  def create
    @administration = Administration.new(administration_params)

    respond_to do |format|
      if @administration.save
        format.html { redirect_to @administration, notice: "Administration créée avec succès !" }
        format.json { render :show, status: :created, location: @administration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @administration.update(administration_params)
        format.html { redirect_to @administration, notice: "Administration mise à jour avec succès." }
        format.json { render :show, status: :ok, location: @administration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administration.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_user
    params.require(:email)
    user = User.where(email: params[:email]).first()

    if user
        if current_user.role_root?
            user.administration = @administration
        elsif current_user.role_manager? and (user.administration_id == nil or user.administration_id == current_user.administration_id)
            user.administration = @administration
        else
            flash[:error] = "L'utilisateur n'existe pas !"
            redirect_to request.referer
        end

        if user.save
            flash[:notice] = "Utilisateur ajouté avec succès !"
        else
            flash[:error] = user.errors
        end
    else
        flash[:error] = "L'utilisateur n'existe pas !"
    end
    
    redirect_to request.referer
  end

  def remove_user
    params.require(:user_id)

    user = User.find(params[:user_id])

    if user
        if current_user.role_root?
            user.administration = nil
        elsif current_user.role_manager? and current_user.administration_id == user.administration_id
            user.administration = nil
        end

        if user.save
            flash[:notice] = "Utilisateur supprimé avec succès"
        else
            flash[:error] = user.errors
        end
    else
        flash[:error] = "L'utilisateur n'existe pas"
    end

    redirect_to request.referer
  end

  private
    def set_administration
        @administration = Administration.find(params[:id])
    end

    def administration_params
        params.require(:administration).permit(:nom, :code, :departement, :service)
    end
end

app/helpers/administrations_helper.rb
module AdministrationsHelper
end

app/views/administrations/_form.html.erb
<%= form_with model: administration do |form| %>
  <% if administration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administration.errors.count, "error") %> prohibited this signalement from being saved:</h2>

      <ul>
        <% administration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field fr-input-group">
    <%= form.label :nom, class: "fr-label" %>
    <%= form.text_field :nom, class: "fr-input" %>
  </div>


  <div class="field fr-input-group">
    <%= form.label :code, class: "fr-label" %>
    <%= form.text_field :code, class: "fr-input" %>
  </div>

  <div class="field fr-input-group">
    <%= form.label :departement, 'Département', class: "fr-label" %>
    <%= form.select :departement, (Departements.map do |d| ["#{d[:code]} - #{d[:desc]}", d[:code]] end), {}, {:class => "fr-select" } %>
  </div>

  <div class="field fr-input-group">
    <%= form.label :service, class: "fr-label" %>
    <%= form.text_field :service, class: "fr-input" %>
  </div>

  <div class="actions">
    <%= form.submit action_name == "edit" ? "Enregistrer les modifications" : "Créer l'administration", class: "fr-btn" %>
  </div>
<% end %>

app/views/administrations/edit.html.erb
<h1>Editer une administration</h1>

<%= render 'form', administration: @administration %>

app/views/administrations/index.html.erb
<div class="fr-table">
    <table>
    <caption>Administrations</caption>
    <thead>
        <tr>
        <th>Nom</th>
        <th>Code</th>
        <th>Département</th>
        <th>Service</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @administrations.each do |administration| %>
        <tr>
            <td><%= administration.nom %></td>
            <td><%= administration.code %></td>
            <td><%= administration.departement %></td>
            <td><%= administration.service %></td>
            <td><%= link_to 'Voir', administration, class: "fr-link" %></td>
            <td><%= link_to 'Modifier', edit_administration_path(administration), class: "fr-link" %></td>
            <td><%= link_to 'Supprimer', administration, method: :delete, data: { confirm: 'Etes vous sûre de vouloir supprimer cette administration ?' }, class: "fr-link" %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

<br>

<%= link_to 'Créer une nouvelle administration', new_administration_path, class: "fr-link" %>

app/views/administrations/new.html.erb
<h1>Nouvelle Administration</h1>

<%= render 'form', administration: @administration %>

app/views/administrations/show.html.erb
<h1><%= @administration.nom %></h1>

<div class="fr-table">
    <table>
        <thead>
            <tr>
                <th>Code SRJ</th>
                <th>Département</th>
                <th>Service</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%= @administration.code %></td>
                <td><%= @administration.departement %></td>
                <td><%= @administration.service %></td>
            </tr>
        </tbody>
    </table>
</div>

<h2>Membres</h2>

<ul>
    <% @administration.users.each do |user| %>
        <li><%= user.email %> - <%= link_to 'Supprimer', remove_user_from_administration_path(user_id: user.id), method: 'DELETE', class: 'fr-link' %></li>
    <% end %>
</ul>

<%= form_with url: add_user_to_administration_path do |form| %>
    <div class="field fr-input-group">
        <%= form.label :email, class: "fr-label" %>
        <%= form.text_field :email, class: "fr-input ip-autocomplete-input", 'data-ip-autocomplete-input-source-api-users': true, autocomplete: 'off' %>
        <div class="ip-autocomplete-input-list"></div>
    </div>
    <%= form.submit "Ajouter l'utilisateur", class: "fr-btn" %>
<% end %>

<%= link_to "Retour", administrations_path, class: "fr-link" %> | 
<%= link_to "Modifier", edit_administration_path(@administration), class: "fr-link" %>