config/routes.rb
Rails.application.routes.draw do
  resources :administrations
  post '/administrations/:id/users', to: 'administrations#add_user', as: 'add_user_to_administration'
  delete '/administrations/:id/users/:user_id', to: 'administrations#remove_user', as: 'remove_user_from_administration'

  resources :signalements do
    member do
        post :publish
    end
  end
  
  devise_for :users, path: 'account', controllers: { registrations: 'users/registrations' }
  get '/account', to: 'account#show'
  
  resources :users, only: [:index, :show, :update]

  post '/ds/event', to: 'ds#event'
  get '/ds/dossiers', to: 'ds#index'

  get '/srj/nataffs', to: 'srj#nataffs'
  get '/srj/natinfs', to: 'srj#natinfs'

  root "index#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoParquet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "#{controller_name} #{action_name}" %>">
    <header role="banner" class="fr-header">
        <div class="fr-header__body">
            <div class="fr-container">
                <div class="fr-header__body-row">
                    <div class="fr-header__brand fr-enlarge-link">
                        <div class="fr-header__brand-top">
                            <div class="fr-header__logo">
                                <p class="fr-logo">
                                    République<br>Française
                                </p>
                            </div>
                            <div class="fr-header__navbar">
                                <button
                                    class="fr-btn--menu fr-btn"
                                    data-fr-opened="false"
                                    aria-controls="modal-833"
                                    aria-haspopup="menu"
                                    title="Menu"
                                    id="fr-btn-menu-mobile"
                                >
                                    Menu
                                </button>
                            </div>
                        </div>
                        <div class="fr-header__service">
                            <a href="/" title="Accueil - InfoParquet - Ministère de la Justice">
                                <p class="fr-header__service-title">InfoParquet</p>
                            </a>
                            <p class="fr-header__service-tagline">signalement simplifié des contentieux</p>
                        </div>
                    </div>
                </div>
                <div class="fr-header_tools">
                    <div class="fr-header__tools-links">
                        <ul class="fr-links-group">
                            <% if current_user == nil %>
                                <li><a class="fr-link fr-fi-add-circle-line" href="/account/sign_up">Créer un compte</a></li>
                                <li><a class="fr-link fr-fi-lock-line" href="/account/sign_in">Se connecter</a></li>
                            <% else %>
                                <li>
                                    <%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete, class: "fr-link fr-fi-lock-line" %>
                                </li>
                                <li>
                                    <%= link_to "#{current_user.prenom} #{current_user.nom}", account_path, class: 'fr-link fr-fi-account-line' %>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="fr-header__menu fr-modal" id="modal-833" aria-labelledby="fr-btn-menu-mobile">
            <div class="fr-container">
                <button class="fr-link--close fr-link" aria-controls="modal-833">Fermer</button>
                <div class="fr-header__menu-links"></div>
               <nav class="fr-nav" id="navigation-832" role="navigation" aria-label="Menu principal">
                    <ul class="fr-nav__list">
                        <% if current_user %>
                            <% if current_user.role_root? or current_user.administration_id %>
                                <%= tab_link "Mes signalements", signalements_path %>
                            <% end %>
                            <% if current_user.role_root? or current_user.role_root? %>
                                <%= tab_link "Administrations", "/administrations" %>
                            <% end %>
                            <% if ['root', 'manager'].include? current_user.role %>
                                <%= tab_link "Utilisateurs", users_path %>
                            <% end %>
                            <%= tab_link "Aide", "#" %>
                        <% end %>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <main>
        <div class="fr-container">
            <div id="flash_messages">
                <% flash.each do |type,msg| %>
                    <div role="alert" class="fr-alert <%= type == 'notice' ? 'fr-alert--success' : 'fr-alert--error' %>">
                        <%= msg %>
                    </div>
                <% end %>
            </div>
            <%= yield %>
        </div>
    </main>
    <footer class="fr-footer" role="contentinfo" id="footer">
        <div class="fr-container">
            <div class="fr-footer__body">
                <div class="fr-footer__brand fr-enlarge-link">
                    <a href="/" title="Retour à l’accueil">
                        <p class="fr-logo" title="république française">
                            république
                            <br>française
                        </p>
                    </a>
                </div>
                <div class="fr-footer__content">
                    <p class="fr-footer__content-desc"></p>
                    <ul class="fr-footer__content-list">
                        <li class="fr-footer__content-item">
                            <a class="fr-footer__content-link" href="https://legifrance.gouv.fr">legifrance.gouv.fr</a>
                        </li>
                        <li class="fr-footer__content-item">
                            <a class="fr-footer__content-link" href="https://gouvernement.fr">gouvernement.fr</a>
                        </li>
                        <li class="fr-footer__content-item">
                            <a class="fr-footer__content-link" href="https://service-public.fr">service-public.fr</a>
                        </li>
                        <li class="fr-footer__content-item">
                            <a class="fr-footer__content-link" href="https://data.gouv.fr">data.gouv.fr</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="fr-footer__bottom">
                <ul class="fr-footer__bottom-list">
                    <li class="fr-footer__bottom-item">
                        <a class="fr-footer__bottom-link" href="#">Plan du site</a>
                    </li>
                    <li class="fr-footer__bottom-item">
                        <a class="fr-footer__bottom-link" href="#">Accessibilité: non/partiellement/totalement conforme</a>
                    </li>
                    <li class="fr-footer__bottom-item">
                        <a class="fr-footer__bottom-link" href="#">Mentions légales</a>
                    </li>
                    <li class="fr-footer__bottom-item">
                        <a class="fr-footer__bottom-link" href="#">Données personnelles</a>
                    </li>
                    <li class="fr-footer__bottom-item">
                        <a class="fr-footer__bottom-link" href="#">Gestion des cookies</a>
                    </li>
                </ul>
                <div class="fr-footer__bottom-copy">
                    <p>Sauf mention contraire, tous les textes de ce site sont sous <a href="https://github.com/etalab/licence-ouverte/blob/master/LO.md" target="_blank">licence etalab-2.0</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

  </body>
</html>